[build]
  command = "next build"
  publish = "out"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://kumuluz.us12.list-manage.com; style-src 'self'; style-src-attr 'none'; img-src 'self'; font-src 'self'; connect-src 'self'; media-src 'self'; object-src 'none'; frame-src 'none'; frame-ancestors 'none'; base-uri 'none'; form-action 'self' https://kumuluz.us12.list-manage.com; manifest-src 'self'; worker-src 'self'"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), geolocation=(), microphone=(), payment=(), usb=()"

[[plugins]]
  package = "@netlify/plugin-csp-nonce"
  [plugins.inputs]
    reportOnly = false
    strictDynamic = true
    unsafeEval = false
    unsafeInline = false
    self = false
    https = false
    http = false

[[redirects]]
  from = "/interstore/lpc"
  to = "https://lpc.sunesis.si"
  status = 301
  force = true

[[redirects]]
  from = "/:lang/interstore/lpc"
  to = "https://lpc.sunesis.si"
  status = 301
  force = true

[[redirects]]
  from = "/:lang/interstore/lpc/*"
  to = "https://lpc.sunesis.si/:splat"
  status = 301
  force = true


