[build]
  command = "npm run build"
  publish = "public"
  environment = {NODE_VERSION = "18.12.1"}
[[redirects]]
  from = "/interstore/lpc/*"
  to = "https://lpc-generator.netlify.app/:splat"
  status = 200
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com; img-src 'self'; font-src 'self'; object-src 'none'; frame-ancestors 'none';"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains;"
    X-Content-Type-Options = "nosniff"
