[build]
  command = "npm run build"
  publish = "public"
  environment = {NODE_VERSION = "18.12.1"}
[[redirects]]
  from = "/interstore/lpc/*"
  to = "https://lpc-generator.netlify.app/:splat"
  status = 200