[build]
  command = "next build"
  publish = "out"

[[redirects]]
  from = "/interstore/lpc"
  to = "https://lpc.sunesis.si"
  status = 301
  force = true

[[redirects]]
  from = "/:lang/interstore/lpc"
  to = "https://lpc.sunesis.si"
  status = 301
  force = true

[[redirects]]
  from = "/:lang/interstore/lpc/*"
  to = "https://lpc.sunesis.si/:splat"
  status = 301
  force = true


